//generated by gpt
package usercontroller

import (
	"time"
)

var _ = time.Now

type LoginResult struct {
	AccessToken string `json:"access_token"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	Username    string `json:"username"`
}
