address: "127.0.0.1:8891"
env: "debug"
log_level: "trace"


redis:
  address: "127.0.0.1:6379"
  max_idle: 50
  idle_timeout: 240
  timeout: 30

db:
  bike:
    database: bike
    username: root
    password: "0707"
    host: "127.0.0.1"
    port: 3306