address:
  127.0.0.1:8890

db:
  bike:
    database: bike
    host: 127.0.0.1
    password: "0707"
    port: 3306
    username: root

env:
  debug

log:
  level: trace

log_level:
  trace

redis:
  address: 127.0.0.1:6379
  idle_timeout: 240
  max_idle: 50
  timeout: 30

report:
  address: ""
  level: ""
  kafka_topic: ""
  kafka_brokers: ""

push_ip: "192.168.0.112:8891"
# push_ip: "192.168.43.50:8891"
