// generated by ginpt
package bike

import (
	"bytes"
	"database/sql"
	"fmt"
	"time"

	"github.com/domego/ginkits/db"
	"github.com/domego/ginkits/redis"
	"github.com/domego/gokits"
	"github.com/domego/gokits/log"
	"github.com/domego/gorp"
)

var _ = time.Now
var _ = fmt.Println
var _ = sql.ErrNoRows
var _ = bytes.NewBuffer
var _ = utils.Int32

type Admin struct {
	Id          int32     `db:"id" json:"id"`
	Username    string    `db:"username" json:"username"`
	Name        string    `db:"name" json:"name"`
	Password    string    `db:"password" json:"password"`
	IsAdmin     int32     `db:"is_admin" json:"is_admin"`
	LastLoginTs int64     `db:"last_login_ts" json:"last_login_ts"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	Deleted     byte      `db:"deleted" json:"deleted"`

	_db *db.DBInfo      `db:"-"`
	_tx *db.Transaction `db:"-"`
}

func NewAdmin() *Admin {
	obj := NewAdminWithoutDB()
	obj.SetDBInfo()
	return obj
}

func NewAdminWithoutDB() *Admin {
	obj := &Admin{}
	return obj
}

func (obj *Admin) SetDBInfo() {
	database := GetDB()
	obj._db = &db.DBInfo{
		DB:    database.DB,
		DbMap: database.DbMap,
	}
}

func (obj *Admin) SetTransaction(tx *db.Transaction) {
	obj._tx = tx
}

func (obj *Admin) GetSqlExecutor() gorp.SqlExecutor {
	if obj._tx != nil {
		return obj._tx
	}
	return obj._db
}

func (obj *Admin) PrimaryCacheKey() string {
	return fmt.Sprintf("bike:orm:admin:id:%v", obj.Id)
}

func (obj *Admin) SaveToCache() error {
	if RedisClient != nil {
		return rediskits.SetModelToCache(RedisClient, obj.PrimaryCacheKey(), obj, DefaultCacheTTL)
	}
	return nil
}

func (obj *Admin) DeleteCache() error {
	if RedisClient != nil {
		return rediskits.DeleteCache(RedisClient, obj.PrimaryCacheKey(), 3)
	}
	return nil
}

func (obj *Admin) Insert() {
	database := obj.GetSqlExecutor()

	obj.CreatedAt = time.Now()

	obj.UpdatedAt = time.Now()

	err := database.Insert(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *Admin) Update() {
	var err error
	database := obj.GetSqlExecutor()

	obj.UpdatedAt = time.Now()

	_, err = database.Update(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *Admin) Delete() {

	obj.Deleted = 1

	obj.Update()

}

func GetAdminWhere(cond string, args ...interface{}) []*Admin {
	objs := []*Admin{}
	database := GetDB()
	_, err := database.Select(&objs, "SELECT `id`, `username`, `name`, `password`, `is_admin`, `last_login_ts`, `created_at`, `updated_at`, `deleted` FROM `admin` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	for _, obj := range objs {
		obj.SetDBInfo()
	}
	return objs
}

func GetAdminCount(cond string, args ...interface{}) int64 {
	database := GetDB()
	cnt, err := database.SelectInt("SELECT count(1) FROM `admin` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	return cnt
}

func GetAdminFirst(cond string, args ...interface{}) *Admin {
	obj := &Admin{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `username`, `name`, `password`, `is_admin`, `last_login_ts`, `created_at`, `updated_at`, `deleted` FROM `admin` WHERE "+cond+" LIMIT 1", args...)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetAdminByField(name string, field interface{}) *Admin {
	obj := &Admin{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `username`, `name`, `password`, `is_admin`, `last_login_ts`, `created_at`, `updated_at`, `deleted` FROM `admin` WHERE `"+name+"`=?", field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetAdminByFieldWithCondition(name, cond string, field interface{}) *Admin {
	obj := &Admin{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `username`, `name`, `password`, `is_admin`, `last_login_ts`, `created_at`, `updated_at`, `deleted` FROM `admin` WHERE `"+name+"`=? "+cond, field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetAdmin(key int32) *Admin {
	obj := &Admin{}
	var notFound = true
	var err error
	if RedisClient != nil {
		obj.Id = key
		notFound = rediskits.GetCacheToModel(RedisClient, obj.PrimaryCacheKey(), obj)
	}
	if notFound {
		database := GetDB()
		err = database.SelectOne(obj, "SELECT `id`, `username`, `name`, `password`, `is_admin`, `last_login_ts`, `created_at`, `updated_at`, `deleted` FROM `admin` WHERE `id`=?", key)
		if err != nil {
			if err.Error() == sql.ErrNoRows.Error() {
				return nil
			}
			panic(err)
		}
	}
	if notFound && RedisClient != nil {
		if err = obj.SaveToCache(); err != nil {
			log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
		}
	}
	obj.SetDBInfo()
	return obj
}
