// generated by ginpt
package bike

import (
	"bytes"
	"database/sql"
	"fmt"
	"time"

	"github.com/domego/ginkits/db"
	"github.com/domego/ginkits/redis"
	"github.com/domego/gokits"
	"github.com/domego/gokits/log"
	"github.com/domego/gorp"
)

var _ = time.Now
var _ = fmt.Println
var _ = sql.ErrNoRows
var _ = bytes.NewBuffer
var _ = utils.Int32

type UserMeta struct {
	Id        int32     `db:"id" json:"id"`
	Uid       int32     `db:"uid" json:"uid"`
	Sex       string    `db:"sex" json:"sex"`
	Avatar    string    `db:"avatar" json:"avatar"`
	Bio       string    `db:"bio" json:"bio"`
	CardName  string    `db:"card_name" json:"card_name"`
	CardId    string    `db:"card_id" json:"card_id"`
	LongiTude string    `db:"longi_tude" json:"longi_tude"`
	LatiTude  string    `db:"lati_tude" json:"lati_tude"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	Deleted   byte      `db:"deleted" json:"deleted"`

	_db *db.DBInfo      `db:"-"`
	_tx *db.Transaction `db:"-"`
}

func NewUserMeta() *UserMeta {
	obj := NewUserMetaWithoutDB()
	obj.SetDBInfo()
	return obj
}

func NewUserMetaWithoutDB() *UserMeta {
	obj := &UserMeta{}
	return obj
}

func (obj *UserMeta) SetDBInfo() {
	database := GetDB()
	obj._db = &db.DBInfo{
		DB:    database.DB,
		DbMap: database.DbMap,
	}
}

func (obj *UserMeta) SetTransaction(tx *db.Transaction) {
	obj._tx = tx
}

func (obj *UserMeta) GetSqlExecutor() gorp.SqlExecutor {
	if obj._tx != nil {
		return obj._tx
	}
	return obj._db
}

func (obj *UserMeta) PrimaryCacheKey() string {
	return fmt.Sprintf("bike:orm:user_meta:id:%v", obj.Id)
}

func (obj *UserMeta) SaveToCache() error {
	if RedisClient != nil {
		return rediskits.SetModelToCache(RedisClient, obj.PrimaryCacheKey(), obj, DefaultCacheTTL)
	}
	return nil
}

func (obj *UserMeta) DeleteCache() error {
	if RedisClient != nil {
		return rediskits.DeleteCache(RedisClient, obj.PrimaryCacheKey(), 3)
	}
	return nil
}

func (obj *UserMeta) Insert() {
	database := obj.GetSqlExecutor()

	obj.CreatedAt = time.Now()

	obj.UpdatedAt = time.Now()

	err := database.Insert(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *UserMeta) Update() {
	var err error
	database := obj.GetSqlExecutor()

	obj.UpdatedAt = time.Now()

	_, err = database.Update(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *UserMeta) Delete() {

	obj.Deleted = 1

	obj.Update()

}

func GetUserMetaWhere(cond string, args ...interface{}) []*UserMeta {
	objs := []*UserMeta{}
	database := GetDB()
	_, err := database.Select(&objs, "SELECT `id`, `uid`, `sex`, `avatar`, `bio`, `card_name`, `card_id`, `longi_tude`, `lati_tude`, `created_at`, `updated_at`, `deleted` FROM `user_meta` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	for _, obj := range objs {
		obj.SetDBInfo()
	}
	return objs
}

func GetUserMetaCount(cond string, args ...interface{}) int64 {
	database := GetDB()
	cnt, err := database.SelectInt("SELECT count(1) FROM `user_meta` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	return cnt
}

func GetUserMetaFirst(cond string, args ...interface{}) *UserMeta {
	obj := &UserMeta{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `uid`, `sex`, `avatar`, `bio`, `card_name`, `card_id`, `longi_tude`, `lati_tude`, `created_at`, `updated_at`, `deleted` FROM `user_meta` WHERE "+cond+" LIMIT 1", args...)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetUserMetaByField(name string, field interface{}) *UserMeta {
	obj := &UserMeta{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `uid`, `sex`, `avatar`, `bio`, `card_name`, `card_id`, `longi_tude`, `lati_tude`, `created_at`, `updated_at`, `deleted` FROM `user_meta` WHERE `"+name+"`=?", field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetUserMetaByFieldWithCondition(name, cond string, field interface{}) *UserMeta {
	obj := &UserMeta{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `uid`, `sex`, `avatar`, `bio`, `card_name`, `card_id`, `longi_tude`, `lati_tude`, `created_at`, `updated_at`, `deleted` FROM `user_meta` WHERE `"+name+"`=? "+cond, field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetUserMeta(key int32) *UserMeta {
	obj := &UserMeta{}
	var notFound = true
	var err error
	if RedisClient != nil {
		obj.Id = key
		notFound = rediskits.GetCacheToModel(RedisClient, obj.PrimaryCacheKey(), obj)
	}
	if notFound {
		database := GetDB()
		err = database.SelectOne(obj, "SELECT `id`, `uid`, `sex`, `avatar`, `bio`, `card_name`, `card_id`, `longi_tude`, `lati_tude`, `created_at`, `updated_at`, `deleted` FROM `user_meta` WHERE `id`=?", key)
		if err != nil {
			if err.Error() == sql.ErrNoRows.Error() {
				return nil
			}
			panic(err)
		}
	}
	if notFound && RedisClient != nil {
		if err = obj.SaveToCache(); err != nil {
			log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
		}
	}
	obj.SetDBInfo()
	return obj
}
