// generated by ginpt
package bike

import (
	"bytes"
	"database/sql"
	"fmt"
	"time"

	"github.com/domego/ginkits/db"
	"github.com/domego/ginkits/redis"
	"github.com/domego/gokits"
	"github.com/domego/gokits/log"
	"github.com/domego/gorp"
)

var _ = time.Now
var _ = fmt.Println
var _ = sql.ErrNoRows
var _ = bytes.NewBuffer
var _ = utils.Int32

type User struct {
	Id        int32     `db:"id" json:"id"`
	Username  string    `db:"username" json:"username"`
	Phone     string    `db:"phone" json:"phone"`
	Password  string    `db:"password" json:"password"`
	Email     string    `db:"email" json:"email"`
	Status    byte      `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	Deleted   byte      `db:"deleted" json:"deleted"`

	_db *db.DBInfo      `db:"-"`
	_tx *db.Transaction `db:"-"`
}

func NewUser() *User {
	obj := NewUserWithoutDB()
	obj.SetDBInfo()
	return obj
}

func NewUserWithoutDB() *User {
	obj := &User{}
	return obj
}

func (obj *User) SetDBInfo() {
	database := GetDB()
	obj._db = &db.DBInfo{
		DB:    database.DB,
		DbMap: database.DbMap,
	}
}

func (obj *User) SetTransaction(tx *db.Transaction) {
	obj._tx = tx
}

func (obj *User) GetSqlExecutor() gorp.SqlExecutor {
	if obj._tx != nil {
		return obj._tx
	}
	return obj._db
}

func (obj *User) PrimaryCacheKey() string {
	return fmt.Sprintf("bike:orm:user:id:%v", obj.Id)
}

func (obj *User) SaveToCache() error {
	if RedisClient != nil {
		return rediskits.SetModelToCache(RedisClient, obj.PrimaryCacheKey(), obj, DefaultCacheTTL)
	}
	return nil
}

func (obj *User) DeleteCache() error {
	if RedisClient != nil {
		return rediskits.DeleteCache(RedisClient, obj.PrimaryCacheKey(), 3)
	}
	return nil
}

func (obj *User) Insert() {
	database := obj.GetSqlExecutor()

	obj.CreatedAt = time.Now()

	obj.UpdatedAt = time.Now()

	err := database.Insert(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *User) Update() {
	var err error
	database := obj.GetSqlExecutor()

	obj.UpdatedAt = time.Now()

	_, err = database.Update(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *User) Delete() {

	obj.Deleted = 1

	obj.Update()

}

func GetUserWhere(cond string, args ...interface{}) []*User {
	objs := []*User{}
	database := GetDB()
	_, err := database.Select(&objs, "SELECT `id`, `username`, `phone`, `password`, `email`, `status`, `created_at`, `updated_at`, `deleted` FROM `user` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	for _, obj := range objs {
		obj.SetDBInfo()
	}
	return objs
}

func GetUserCount(cond string, args ...interface{}) int64 {
	database := GetDB()
	cnt, err := database.SelectInt("SELECT count(1) FROM `user` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	return cnt
}

func GetUserFirst(cond string, args ...interface{}) *User {
	obj := &User{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `username`, `phone`, `password`, `email`, `status`, `created_at`, `updated_at`, `deleted` FROM `user` WHERE "+cond+" LIMIT 1", args...)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetUserByField(name string, field interface{}) *User {
	obj := &User{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `username`, `phone`, `password`, `email`, `status`, `created_at`, `updated_at`, `deleted` FROM `user` WHERE `"+name+"`=?", field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetUserByFieldWithCondition(name, cond string, field interface{}) *User {
	obj := &User{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `username`, `phone`, `password`, `email`, `status`, `created_at`, `updated_at`, `deleted` FROM `user` WHERE `"+name+"`=? "+cond, field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetUser(key int32) *User {
	obj := &User{}
	var notFound = true
	var err error
	if RedisClient != nil {
		obj.Id = key
		notFound = rediskits.GetCacheToModel(RedisClient, obj.PrimaryCacheKey(), obj)
	}
	if notFound {
		database := GetDB()
		err = database.SelectOne(obj, "SELECT `id`, `username`, `phone`, `password`, `email`, `status`, `created_at`, `updated_at`, `deleted` FROM `user` WHERE `id`=?", key)
		if err != nil {
			if err.Error() == sql.ErrNoRows.Error() {
				return nil
			}
			panic(err)
		}
	}
	if notFound && RedisClient != nil {
		if err = obj.SaveToCache(); err != nil {
			log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
		}
	}
	obj.SetDBInfo()
	return obj
}
