// generated by ginpt
package bike

import (
	"bytes"
	"database/sql"
	"fmt"
	"time"

	"github.com/domego/ginkits/db"
	"github.com/domego/ginkits/redis"
	"github.com/domego/gokits"
	"github.com/domego/gokits/log"
	"github.com/domego/gorp"
)

var _ = time.Now
var _ = fmt.Println
var _ = sql.ErrNoRows
var _ = bytes.NewBuffer
var _ = utils.Int32

type TopLog struct {
	Id        int32     `db:"id" json:"id"`
	Uid       int32     `db:"uid" json:"uid"`
	Count     int32     `db:"count" json:"count"`
	TopTs     int64     `db:"top_ts" json:"top_ts"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	Deleted   byte      `db:"deleted" json:"deleted"`

	_db *db.DBInfo      `db:"-"`
	_tx *db.Transaction `db:"-"`
}

func NewTopLog() *TopLog {
	obj := NewTopLogWithoutDB()
	obj.SetDBInfo()
	return obj
}

func NewTopLogWithoutDB() *TopLog {
	obj := &TopLog{}
	return obj
}

func (obj *TopLog) SetDBInfo() {
	database := GetDB()
	obj._db = &db.DBInfo{
		DB:    database.DB,
		DbMap: database.DbMap,
	}
}

func (obj *TopLog) SetTransaction(tx *db.Transaction) {
	obj._tx = tx
}

func (obj *TopLog) GetSqlExecutor() gorp.SqlExecutor {
	if obj._tx != nil {
		return obj._tx
	}
	return obj._db
}

func (obj *TopLog) PrimaryCacheKey() string {
	return fmt.Sprintf("bike:orm:top_log:id:%v", obj.Id)
}

func (obj *TopLog) SaveToCache() error {
	if RedisClient != nil {
		return rediskits.SetModelToCache(RedisClient, obj.PrimaryCacheKey(), obj, DefaultCacheTTL)
	}
	return nil
}

func (obj *TopLog) DeleteCache() error {
	if RedisClient != nil {
		return rediskits.DeleteCache(RedisClient, obj.PrimaryCacheKey(), 3)
	}
	return nil
}

func (obj *TopLog) Insert() {
	database := obj.GetSqlExecutor()

	obj.CreatedAt = time.Now()

	obj.UpdatedAt = time.Now()

	err := database.Insert(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *TopLog) Update() {
	var err error
	database := obj.GetSqlExecutor()

	obj.UpdatedAt = time.Now()

	_, err = database.Update(obj)
	if err != nil {
		panic(err)
	}
	if err = obj.SaveToCache(); err != nil {
		log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
	}
}

func (obj *TopLog) Delete() {

	obj.Deleted = 1

	obj.Update()

}

func GetTopLogWhere(cond string, args ...interface{}) []*TopLog {
	objs := []*TopLog{}
	database := GetDB()
	_, err := database.Select(&objs, "SELECT `id`, `uid`, `count`, `top_ts`, `created_at`, `updated_at`, `deleted` FROM `top_log` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	for _, obj := range objs {
		obj.SetDBInfo()
	}
	return objs
}

func GetTopLogCount(cond string, args ...interface{}) int64 {
	database := GetDB()
	cnt, err := database.SelectInt("SELECT count(1) FROM `top_log` WHERE "+cond, args...)
	if err != nil {
		panic(err)
	}
	return cnt
}

func GetTopLogFirst(cond string, args ...interface{}) *TopLog {
	obj := &TopLog{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `uid`, `count`, `top_ts`, `created_at`, `updated_at`, `deleted` FROM `top_log` WHERE "+cond+" LIMIT 1", args...)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetTopLogByField(name string, field interface{}) *TopLog {
	obj := &TopLog{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `uid`, `count`, `top_ts`, `created_at`, `updated_at`, `deleted` FROM `top_log` WHERE `"+name+"`=?", field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetTopLogByFieldWithCondition(name, cond string, field interface{}) *TopLog {
	obj := &TopLog{}
	database := GetDB()
	err := database.SelectOne(obj, "SELECT `id`, `uid`, `count`, `top_ts`, `created_at`, `updated_at`, `deleted` FROM `top_log` WHERE `"+name+"`=? "+cond, field)
	if err != nil {
		if err.Error() == sql.ErrNoRows.Error() {
			return nil
		}
		panic(err)
	}
	obj.SetDBInfo()
	return obj
}

func GetTopLog(key int32) *TopLog {
	obj := &TopLog{}
	var notFound = true
	var err error
	if RedisClient != nil {
		obj.Id = key
		notFound = rediskits.GetCacheToModel(RedisClient, obj.PrimaryCacheKey(), obj)
	}
	if notFound {
		database := GetDB()
		err = database.SelectOne(obj, "SELECT `id`, `uid`, `count`, `top_ts`, `created_at`, `updated_at`, `deleted` FROM `top_log` WHERE `id`=?", key)
		if err != nil {
			if err.Error() == sql.ErrNoRows.Error() {
				return nil
			}
			panic(err)
		}
	}
	if notFound && RedisClient != nil {
		if err = obj.SaveToCache(); err != nil {
			log.Errorf("[CacheKey:%s], %s", obj.PrimaryCacheKey(), err)
		}
	}
	obj.SetDBInfo()
	return obj
}
