//generated by gpt
package usercontroller

import (
	"time"
)

var _ = time.Now

type UserList struct {
	List []*UserProfile `json:"list"`
}

type UserProfile struct {
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
	CardId   string `json:"card_id"`
	CardName string `json:"card_name"`
	Email    string `json:"email"`
	Id       int32  `json:"id"`
	Phone    string `json:"phone"`
	Sex      string `json:"sex"`
	Status   string `json:"status"`
	Username string `json:"username"`
}
