//generated by gpt
package usecontroller

import (
	"time"
)

var _ = time.Now

type Detail struct {
	AllTs     string `json:"all_ts"`
	Amount    string `json:"amount"`
	BikeId    int32  `json:"bike_id"`
	EndTs     string `json:"end_ts"`
	LatiTude  string `json:"lati_tude"`
	LongiTude string `json:"longi_tude"`
	StartTs   string `json:"start_ts"`
}

type UseDetail struct {
	List []*Detail `json:"list"`
}
