//generated by gpt
package usecontroller

import (
	"time"
)

var _ = time.Now

type Detail struct {
	Amount    int32  `json:"amount"`
	BikeId    int32  `json:"bike_id"`
	EndTs     int64  `json:"end_ts"`
	LatiTude  string `json:"lati_tude"`
	LongiTude string `json:"longi_tude"`
	StartTs   int64  `json:"start_ts"`
}

type UseDetail struct {
	List []*Detail `json:"list"`
}
