//generated by gpt
package bikecontroller

import (
	"time"
)

var _ = time.Now

type AlarmInfo struct {
	AlarmTs string `json:"alarm_ts"`
	ById    int32  `json:"by_id"`
	Id      int32  `json:"id"`
	MhCount string `json:"mh_count"`
	SwCount string `json:"sw_count"`
}

type AlarmList struct {
	List []*AlarmInfo `json:"list"`
}
